In [1]:
import numpy as np

In [6]:
a=np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [13]:
n=np.full((10,10),5)
print(n)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [14]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,5,4],[3,2,1]])
z=x+y
print(z)

[[7 7 7]
 [7 7 7]]


In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])
split=np.split(arr,3)
print(split)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [3]:
ar=np.linspace(0,1,100)
print(ar)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [5]:
x=np.linspace(0,1,9)
print(x)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [18]:
#With logic:

toss=np.random.randint(0,2,10000)
print(toss)
head=0
tail=0

for i in range(len(toss)):
    if toss[i]==1:
        head+=i
    else:
        tail+=i
print("Head: ",head)
print("Tail: ",tail)
    

[0 1 0 ... 0 0 0]
Head:  24634769
Tail:  25360231


In [22]:
#Without logic:

toss = np.random.randint(0, 2, 100000)
head = np.sum(toss)
tail = len(toss) - head

print("Heads:", head)
print("Tails:", tail)


Heads: 50178
Tails: 49822


In [28]:
arr=np.linspace(0,1,27).reshape(3,3,3)
print(arr)

[[[0.         0.03846154 0.07692308]
  [0.11538462 0.15384615 0.19230769]
  [0.23076923 0.26923077 0.30769231]]

 [[0.34615385 0.38461538 0.42307692]
  [0.46153846 0.5        0.53846154]
  [0.57692308 0.61538462 0.65384615]]

 [[0.69230769 0.73076923 0.76923077]
  [0.80769231 0.84615385 0.88461538]
  [0.92307692 0.96153846 1.        ]]]


In [43]:
#Sum 2 Array:

arr= np.arange(1,11)
arr1=np.random.choice(arr,size=(4,5))
num=np.linspace(0,1,20).reshape(4,5)
print(arr1+num)

[[ 4.          8.05263158  8.10526316  5.15789474  2.21052632]
 [ 1.26315789 10.31578947  4.36842105 10.42105263  7.47368421]
 [ 3.52631579  3.57894737  7.63157895  6.68421053  9.73684211]
 [ 9.78947368  4.84210526  4.89473684  8.94736842  3.        ]]


In [ ]:
x=np.random